name: Code Coverage Check

on:
  #pull_request:
  push:
    branches:
      - main

jobs:
  check_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Test with Gradle
        run: ./gradlew clean build

      - name: Extract Coverage Percentage
        id: extract_coverage
        run: |
          coverage=$(grep -oP '(?<=<td>Total</td><td class="bar">).*(?=</td><td class="ctr2">)' < ./build/jacocoHtml/index.html)
          echo "::set-output name=coverage::$coverage"

      - name: Check Coverage Threshold
        run: |
          if (( $(echo "${{ steps.extract_coverage.outputs.coverage }} < 80" | bc -l) )); then
            echo "Error: Test coverage is below 80% threshold"
            exit 1
          fi
