name: Code Coverage Check

on:
  #pull_request:
  push:
    branches:
      - main

jobs:
  check_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Test with Gradle
        run: ./gradlew clean build
