name: Code Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'

      - name: Build and Test with Gradle
        run: ./gradlew clean build

      - name: Get Coverage Percentage
        id: coverage
        run: echo "::set-output name=coverage::$(awk '/Overall/ {print substr($4, 1, length($4)-1)}' <(tail -n 4 build/reports/jacoco/test/jacocoTestReport.xml))"

      - name: Check Coverage Threshold
        run: |
          if (( $(echo "${{ steps.coverage.outputs.coverage }} < 80" | bc -l) )); then
            echo "Error: Test coverage is below 80% threshold"
            exit 1
          fi
